apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: tweet
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhYmR1bHJhaG1hbmVsZmVraS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYW1aeWIyZGpjbVZrT2tKbFpHOXpZVzQzT0Y4PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson