apiVersion: v1
kind: Service
metadata:
  name: valaxy-rtp-service
  namespace: valaxy
spec:
  type: NodePort
  selector:
    app: valaxy-rtp-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30082